name: CI
on:
  push:
    branches:
      - master
jobs:
  CIJob:
    runs-on: ubuntu-latest
    steps:
      - name: Checout repository
        uses: actions/checout@v4

        name: Execute command
        run: echo "Hellow world from Staging!!!"

